from . import sale_margin_line_rule
from . import product_cost_history
from . import account_move
from . import sale_order
from . import sale_order_line
from . import purchase_order_line
from . import product_template
from . import product_product
from . import stock_picking
from . import stock_orderpoint
from . import res_company
from . import res_config_settings
