{
    'name': 'Sale Discount Policy — Farmacias Económicas',
    'version': '19.0.1.2.1',
    'category': 'Sales/Sales',
    'summary': '2% discount for Farmacias Económicas group, excluding restricted brands, scoped to Cancún and Playa del Carmen',
    'author': 'Medicine Depot - Daniel Cervera',
    'license': 'LGPL-3',
    'depends': [
        'sale',
        'sale_management',
        'product',
        'stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/sale_discount_security.xml',
        'data/partner_category_data.xml',
        'data/product_tag_data.xml',
        'data/discount_policy_data.xml',
        'data/restricted_sku_data.xml',
        'views/sale_discount_policy_views.xml',
        'views/product_template_views.xml',
        'views/menu.xml',
        'wizards/restricted_product_import_views.xml',
        'report/discount_verification_report.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
