"""
CORREGIDO — bug de dominio arreglado por revision humana / FIXED — domain bug corrected by human review

Generado por / Generated by: Ollama qwen2.5-coder:7b, servidor ionos, 2026-07-27
Corregido por / Fixed by: Data Migration Architect (revision humana, no regenerado por Ollama), 2026-07-27
Referencia / Reference: docs/OLLAMA_MIGRATION_PLAN.md, seccion 4 (Estrategia ETL Asistida) y seccion 9 (Ejecucion Registrada)
Regla de gobernanza aplicada: todo script generado por Ollama se commitea con su prompt
antes de ejecutarse contra datos reales (ver docs/OLLAMA_MIGRATION_PLAN.md 8.1 / 4).

Prompt original usado / Original prompt used:
    "Rol: Ingeniero ETL Odoo 19. Tarea: escribe una funcion Python breve que use
    xmlrpc.client para leer la cantidad 'A la mano' (On Hand) de stock.quant para
    una lista de product_id, agrupando por producto. Restriccion de nomenclatura:
    toda variable, docstring y log debe decir 'a_la_mano' u 'On Hand'. Esta
    prohibido usar 'disponible', 'stock' o 'existencias' en cualquier identificador
    o texto generado. No incluyas explicacion, solo el codigo."

Revision humana (Data Migration Architect) / Human review:
    - Terminologia: CUMPLE. Solo usa 'a_la_mano' y 'on_hand', cero ocurrencias de
      'disponible'/'stock'/'existencias'.
    - BUG original: la version generada por Ollama pasaba `product_ids` directamente
      como IDs de registros de `stock.quant` en el metodo 'read'. Eso era incorrecto:
      leia registros de stock.quant cuyo ID numerico coincidia con el product_id,
      lo cual es semanticamente incorrecto.
    - CORRECCION APLICADA: se reemplazo 'read' por 'search_read' con un dominio
      explicito `[('product_id', 'in', product_ids), ('location_id.usage', '=', 'internal')]`,
      que si filtra los quants por producto y por ubicaciones internas (excluye
      ubicaciones virtuales de perdida/cliente/proveedor).
    - Estado: APTO para revision de QA / pruebas en 'dev'. Sigue pendiente probarlo
      contra una base real antes de usarlo en 'test'/'prod'.
"""

import xmlrpc.client


def get_a_la_mano_quantity(product_ids, url, db, username, password):
    """Lee la cantidad 'A la mano' (On Hand) de stock.quant, agrupada por producto."""
    common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(url))
    uid = common.authenticate(db, username, password, {})
    models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(url))

    domain = [
        ('product_id', 'in', product_ids),
        ('location_id.usage', '=', 'internal'),
    ]
    on_hand_records = models.execute_kw(
        db, uid, password, 'stock.quant', 'search_read',
        [domain], {'fields': ['product_id', 'quantity']},
    )

    a_la_mano = {}
    for record in on_hand_records:
        product_id = record['product_id'][0]
        quantity = record['quantity']
        a_la_mano[product_id] = a_la_mano.get(product_id, 0) + quantity

    return a_la_mano


# Ejemplo de uso:
# url = 'http://localhost:8069'
# db = 'base_de_datos'
# username = 'usuario'
# password = 'contrasena'
# product_ids = [1, 2, 3]
# a_la_mano = get_a_la_mano_quantity(product_ids, url, db, username, password)
# print(a_la_mano)
